spring:
  main:
    banner-mode: off
  jackson:
    time-zone: GMT+8
mybatis:
  mapper-locations:
    - classpath*:com/summer/common/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
hikaricp:
  common:
    properties:
      min-idle: 1
      max-life-time: 120000
      idle-time-out: 60000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    propagation:
      consume: b3
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      slo:
        http.server.requests: 10ms,100ms,1s,10s
      maximum-expected-value:
        http.server.requests: 30s
pointcut:
  controller:
    property: execution(public * com.summer.tool.controller.*Controller.*(..))
  dao:
    property: execution(public * com.summer.tool.dao.*DAO.*(..))
  handler:
    property: execution(public * com.summer.common.config.GlobalExceptionHandler.*(..))
server:
  tomcat:
    mbeanregistry:
      enabled: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none