server:
  port: 1000
spring:
  dynamic-datasource:
    data-source-list:
      - name: andi
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/andi?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        connection-test-query: SELECT 1